language: node_js
node_js: "8.9.3"

before_install:
  - rm -rf node_modules

stages:
  - &stage
    name: test
  - <<: *stage
    name: deploy-firebase
    if: branch = development AND type = push

jobs:
  include:
    - stage: test
      script:
       - echo "test"
    - stage: deploy-firebase
      install:
       - npm install -g firebase-tools
       - npm install -g angular-cli
      script:
        - echo "Build!";
        - npm install;
        - ng build --prod;
        - echo "deploy to firebase"
        - firebase deploy --token $livestarter
