export const newStreamObj = {
  live_stream: {
    aspect_ratio_height: 1080,
    aspect_ratio_width: 1920,
    billing_mode: 'pay_as_you_go',
    broadcast_location: 'eu_germany',
    closed_caption_type: 'none',
    delivery_method: 'push',
    delivery_protocols: [
      'rtmp',
      'rtsp',
      'wowz'
    ],
    delivery_type: 'single-bitrate',
    disable_authentication: false,
    encoder: 'wowza_gocoder',
    hosted_page: false,
    hosted_page_description: '',
    hosted_page_logo_image: '',
    hosted_page_sharing_icons: false,
    hosted_page_title: '',
    low_latency: true,
    name: 'My Live Stream4',
    password: '',
    player_countdown: false,
    player_countdown_at: '',
    player_logo_image: '',
    player_logo_position: 'top-right',
    player_responsive: true,
    player_type: 'wowza_player',
    player_video_poster_image: '',
    player_width: 640,
    recording: false,
    remove_hosted_page_logo_image: true,
    remove_player_logo_image: true,
    remove_player_video_poster_image: true,
    source_url: '',
    target_delivery_protocol: 'hls-https',
    transcoder_type: 'transcoded',
    use_stream_source: false,
    username: 'client2',
    video_fallback: false
  }
};
